# Generated by Django 3.0.7 on 2020-06-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccy', models.CharField(max_length=20)),
                ('ccy_rounding_places', models.FloatField()),
                ('ccy_rounding_direction', models.FloatField()),
                ('index', models.CharField(max_length=20)),
                ('notional', models.FloatField()),
                ('spread', models.FloatField()),
                ('start', models.DateField()),
                ('maturity', models.DateField()),
                ('payhols', models.CharField(max_length=20)),
                ('paymarch', models.CharField(max_length=20)),
                ('trade_id', models.CharField(max_length=20)),
                ('product_type', models.CharField(max_length=50)),
                ('trade_date', models.DateField()),
            ],
        ),
    ]
